FROM eclipse-temurin:21-jdk AS dev
WORKDIR /app

RUN apt-get update && apt-get install -y dos2unix curl unzip && rm -rf /var/lib/apt/lists/*

COPY gradlew .
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradle.properties .
COPY gradle ./gradle

RUN dos2unix gradlew && chmod +x gradlew

COPY src ./src

EXPOSE 8080

CMD ["./gradlew", "quarkusDev"]