services:
  backend:
    image: edc-project-initializer-backend:dev
    build:
      context: backend
      dockerfile: src/main/docker/Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - '**/build/'
            - '**/.gradle/'
        - action: rebuild
          path: ./backend/build.gradle.kts
        - action: rebuild
          path: ./backend/settings.gradle.kts

  frontend:
    image: edc-project-initializer-frontend:dev
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./frontend/package.json